### ISSUE TITLE
Dictionary error when generating report

### ISSUE THREAD

**Issue by bkochendorfer** [nccgroup/Scout2#101]
Getting the following when running on master. Enabled debug to get some information about what rule is running, hope this helps!

```python
Processing iam rule: "Root account has active keys"
Traceback (most recent call last):
  File "Scout2.py", line 267, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 204, in main
    create_report_metadata(aws_config, services)
  File "/**/scout2/Scout2/AWSScout2/utils.py", line 272, in create_report_metadata
    manage_dictionary(aws_config['metadata'][s]['summaries'][resource], 'risks', [])
KeyError: u'summaries'
(scout2)
```

I did a little research and was able to build from v2.0.0rc4 but not 5 or master. https://github.com/nccgroup/Scout2/compare/v2.0.0rc4...v2.0.0rc5

**Comment by laprice** [comment]
Came across the same issue. Same work around. I went looking for where the aws_config object gets constructed but didn't see anything obvious in the diffs. Nowhere that it says creates it with summaries before and without after. 

Wondering if it is even getting the dictionary at all at that point.

**Comment by l01cd3v** [comment]
Can you please pull the latest code from the dev branch, run the tool with --debug, and share the output with me?

**Comment by l01cd3v** [comment]
Closing for now due to no activity
