### ISSUE TITLE
Key Error adding security group names to ec2 grants

### ISSUE THREAD

**Issue by MrSecure** [nccgroup/Scout2#108]
I think there's a problem with `add_security_group_name_to_ec2_grants()` - it appears that a security group that refers to another security group which has not yet been visited causes a failure to find a key in the data set.  Is a two-pass approach needed - enumerate all of the SG's first, then handle rules & relationships?

In the output below, building the data for `sg-8d000aaa` fails, since it cannot find a key for `sg-c010c010`.

Modification:
 * based on 83a5717de9c361814eb353eeb822028af8928543   -  dev branch

```
--- a/AWSScout2/utils.py
+++ b/AWSScout2/utils.py
@@ -174,6 +174,7 @@ def go_to_and_do(aws_config, current_config, path, current_path, callback, callb
                 # keep track of where we are...
                 tmp = copy.deepcopy(current_path)
                 tmp.append(value)
+                printDebug('.'.join(current_path))
                 go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
```

Resulting Output:
 * addresses and AWS resource IDs partially scrubbed.

```
$ python ./Scout2.py --csv-credentials /vagrant/scout-creds.csv --debug --regions us-west-2 --services iam ec2 rds s3
...

regions.us-west-2.vpcs.vpc-b1010101.security_groups
regions.us-west-2.vpcs.vpc-b1010101.security_groups.sg-8d000aaa.rules
regions.us-west-2.vpcs.vpc-b1010101.security_groups.sg-8d000aaa.rules.ingress.protocols
regions.us-west-2.vpcs.vpc-b1010101.security_groups.sg-8d000aaa.rules.ingress.protocols.UDP.ports
Error
Traceback (most recent call last):
  File "/vagrant/Scout2/AWSScout2/utils_ec2.py", line 26, in analyze_ec2_config
    add_security_group_name_to_ec2_grants(ec2_info, aws_account_id)
  File "/vagrant/Scout2/AWSScout2/utils_ec2.py", line 41, in add_security_group_name_to_ec2_grants
    go_to_and_do(ec2_config, None, ['regions', 'vpcs', 'security_groups', 'rules', 'protocols', 'ports', 'security_groups'], [], add_security_group_name_to_ec2_grants_callback, {'AWSAccountId': aws_account_id})
  File "/vagrant/Scout2/AWSScout2/utils.py", line 178, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/vagrant/Scout2/AWSScout2/utils.py", line 178, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/vagrant/Scout2/AWSScout2/utils.py", line 178, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/vagrant/Scout2/AWSScout2/utils.py", line 178, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/vagrant/Scout2/AWSScout2/utils.py", line 178, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/vagrant/Scout2/AWSScout2/utils.py", line 178, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/vagrant/Scout2/AWSScout2/utils.py", line 172, in go_to_and_do
    callback(aws_config, current_config, path, current_path, value, callback_args)
  File "/vagrant/Scout2/AWSScout2/utils_ec2.py", line 53, in add_security_group_name_to_ec2_grants_callback
    ec2_grant['GroupName'] = get_attribute_at(ec2_config, target, 'name')
  File "/vagrant/Scout2/AWSScout2/utils.py", line 140, in get_attribute_at
    config = config[target]
KeyError: 'sg-c010c010'

services.iam.groups
```

JSON extracted from  aws_config.js, selected for the SG which is failing.

```json
$ cat aws_config.json | jq -M '.services.ec2.regions."us-west-2".vpcs."vpc-b1010101".security_groups."sg-8d000aaa"'
{
  "description": "[cfn] miracle-max-sg",
  "id": "sg-8d000aaa",
  "instances": {
    "stopped": [
      "i-9182d956",
      "i-39cea0e1"
    ]
  },
  "name": "miracle-max-2Sg-NCYIO4HNACS3",
  "owner_id": "673930986116",
  "rules": {
    "egress": {
      "count": 1,
      "protocols": {
        "ALL": {
          "ports": {
            "N/A": {
              "cidrs": [
                {
                  "CIDR": "198.51.100.0/24"
                }
              ]
            }
          }
        }
      }
    },
    "ingress": {
      "count": 8,
      "protocols": {
        "TCP": {
          "ports": {
            "1139": {
              "security_groups": [
                {
                  "GroupId": "sg-9249b2f5",
                  "UserId": "673930986116"
                }
              ]
            },
            "2161-2162": {
              "security_groups": [
                {
                  "GroupId": "sg-c010faa7",
                  "UserId": "673930986116"
                }
              ]
            },
            "17778": {
              "security_groups": [
                {
                  "GroupId": "sg-c010faa7",
                  "UserId": "673930986116"
                }
              ]
            },
            "17790": {
              "security_groups": [
                {
                  "GroupId": "sg-c010faa7",
                  "UserId": "673930986116"
                }
              ]
            },
            "8081": {
              "cidrs": [
                {
                  "CIDR": "203.0.113.0/24"
                }
              ]
            }
          }
        },
        "UDP": {
          "ports": {
            "2161-2162": {
              "security_groups": [
                {
                  "GroupId": "sg-c010faa7",
                  "UserId": "673930986116"
                }
              ]
            }
          }
        }
      }
    }
  },
  "used_by": {
    "ec2": {
      "resource_type": {
        "instances": {
          "stopped": [
            "i-91acacac",
            "i-32acacac"
          ]
        }
      }
    }
  }
}
```

**Comment by l01cd3v** [comment]
All data fetching is done before running the add_security_group_name_to_ec2_grants(). My guess is that this error occurs because you limit your run of Scout2 to the us-west-2 region but the missing security group is in a different region.

I will try to repro this error and push code that silently ignores this exception if my guess is right.

**Comment by l01cd3v** [comment]
Actually it looks like AWS prevents referencing security group IDs that are not in the same region/vpc when creating rules. Could you please lookup the failing security group (missing key value) in the console and let me know if it exists or not, whether it's in us-west-2, and whether it's a VPC security group or from a different service?

Thanks

**Comment by MrSecure** [comment]
The security group is in a different VPC, but in the same region, account.

The failure was in `regions.us-west-2.vpcs.vpc-b1010101.security_groups`, failing to find `sg-c010c010` 

```
$ aws --profile scout ec2 describe-security-groups --group-ids sg-c010c010 --filters Name=vpc-id,Values=vpc-b1010101
{
    "SecurityGroups": []
}
$ aws --profile scout ec2 describe-security-groups --group-ids sg-c010c010 | jq -M '.SecurityGroups[] | {VpcId,GroupId}'
{
  "VpcId": "vpc-16161616",
  "GroupId": "sg-c010c010",
}
$
```

Thank you!

**Comment by ericleestewart** [comment]
I've been able to replicate the issue brought up by MrSecure. It occurs because the code that's cataloging the AWS resources is trying to map an entire VPC in a single pass. Unfortunately, it needs to pass through all VPCs grabbing some resources before it can dive deep into each VPC individually. At least that's how it appears from testing so far. Would this project be open to a PR that modifies the cataloging to do a shallow pass through all VPCs before doing a deeper dive through each VPC in a second pass?

**Comment by l01cd3v** [comment]
I was able to repro & understand the issue. I modified the code such that it updates the VPC ID when doing the lookup for the security group name. To do that, I had to update the min version of botocore used to ensure that, when VPC peering happens, the security group's VPC ID is returned in the data structure describing the grant.

Could you please confirm this works for you? You'll need to pull the latest code and may have to update dependencies (pip install -r requirements.txt)

**Comment by MrSecure** [comment]
tested with dev branch at 18add23040c2e1688c74777358cc285ccf792809 and the run completes without error, and the cross-VPC security groups are captured cleanly.  👍 

Thank you!!

**Comment by l01cd3v** [comment]
Thanks !
