### ISSUE TITLE
[dev] TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by d-j-c** [nccgroup/Scout2#139]
When running Scout2 off the dev branch I find that I get the following error:

```
Creating scout2-report/report.html ...
File 'scout2-report/report.html' already exists. Do you want to overwrite it (y/n)? y
'NoneType' object has no attribute '__getitem__'
Index: 0
Path: ['regions', u'ap-southeast-2', 'vpcs', u'vpc-ba1052da', 'instances', u'i-081f2dce914dba5c1', 'network_interfaces', u'eni-b8089cc2', 'PrivateIpAddresses']
Key = PrivateIpAddresses
Value = {u'PrivateDnsName': u'ip-10-25-0-66.ap-southeast-2.compute.internal', u'Primary': True, u'PrivateIpAddress': u'10.25.0.66'}
Path = []
'NoneType' object has no attribute '__getitem__'
Index: 0
Path: ['regions', u'ap-southeast-2', 'vpcs', u'vpc-ba1052da', 'instances', u'i-01f87c5d9535aa480', 'network_interfaces', u'eni-319ba548', 'PrivateIpAddresses']
Key = PrivateIpAddresses
Value = {u'PrivateDnsName': u'ip-10-25-0-92.ap-southeast-2.compute.internal', u'Primary': True, u'PrivateIpAddress': u'10.25.0.92'}
Path = []
Matching EC2 instances and IAM roles...
Analyzing AWS config...
Analyzing AWS config...
Saving data to scout2-report/inc-awsconfig/aws_config.js
Saving config...
File 'scout2-report/inc-awsconfig/aws_config.js' already exists. Do you want to overwrite it (y/n)?
```

Running with `--debug`:

```
Saving config...
Creating scout2-report/report.html ...
Traceback (most recent call last):
  File "/home/d-j-c/dev/clone/Scout2/AWSScout2/rules/preprocessing.py", line 357, in go_to_and_do
    callback(aws_config, current_config, path, current_path, value, callback_args)
  File "/home/d-j-c/dev/clone/Scout2/AWSScout2/rules/preprocessing.py", line 73, in list_ec2_network_attack_surface_callback
    public_ip = current_config['Association']['PublicIp']
TypeError: 'NoneType' object has no attribute '__getitem__'
  
Index: 0
Path: ['regions', u'ap-southeast-2', 'vpcs', u'vpc-ba1052da', 'instances', u'i-081f2dce914dba5c1', 'network_interfaces', u'eni-b8089cc2', 'PrivateIpAddresses']
Key = PrivateIpAddresses
Value = {u'PrivateDnsName': u'ip-10-25-0-66.ap-southeast-2.compute.internal', u'Primary': True, u'PrivateIpAddress': u'10.25.0.66'}
Path = []
Traceback (most recent call last):
  File "/home/d-j-c/dev/clone/Scout2/AWSScout2/rules/preprocessing.py", line 357, in go_to_and_do
    callback(aws_config, current_config, path, current_path, value, callback_args)
  File "/home/d-j-c/dev/clone/Scout2/AWSScout2/rules/preprocessing.py", line 73, in list_ec2_network_attack_surface_callback
    public_ip = current_config['Association']['PublicIp']
TypeError: 'NoneType' object has no attribute '__getitem__'

Index: 0
Path: ['regions', u'ap-southeast-2', 'vpcs', u'vpc-ba1052da', 'instances', u'i-01f87c5d9535aa480', 'network_interfaces', u'eni-319ba548', 'PrivateIpAddresses']
Key = PrivateIpAddresses
Value = {u'PrivateDnsName': u'ip-10-25-0-92.ap-southeast-2.compute.internal', u'Primary': True, u'PrivateIpAddress': u'10.25.0.92'}
Path = []
Matching EC2 instances and IAM roles...
Analyzing AWS config..
```

Looks like the issue lies within `AWSScout2/rules/preprocessing.py`

I put in a print `current_config` at the start of the function `list_ec2_network_attack_surface_callback` and saw the following:

```
Index: 0
Path: ['regions', u'ap-southeast-2', 'vpcs', u'vpc-ba1052da', 'instances', u'i-081f2dce914dba5c1', 'network_interfaces', u'eni-b8089cc2', 'PrivateIpAddresses']
Key = PrivateIpAddresses
Value = {u'PrivateDnsName': u'ip-10-25-0-66.ap-southeast-2.compute.internal', u'Primary': True, u'PrivateIpAddress': u'10.25.0.66'}
Path = []
{u'PrivateIpAddresses': [{u'PrivateDnsName': u'ip-10-25-0-92.ap-southeast-2.compute.internal', u'Primary': True, u'PrivateIpAddress': u'10.25.0.92'}], u'Groups': [{u'GroupName': u'dashboard-svc-sg', u'GroupId': u'sg-d39c2ab6'}], u'Association': None}
Traceback (most recent call last):
  File "/home/d-j-c/dev/clone/Scout2/AWSScout2/rules/preprocessing.py", line 358, in go_to_and_do
    callback(aws_config, current_config, path, current_path, value, callback_args)
  File "/home/d-j-c/dev/clone/Scout2/AWSScout2/rules/preprocessing.py", line 74, in list_ec2_network_attack_surface_callback
    public_ip = current_config['Association']['PublicIp']
TypeError: 'NoneType' object has no attribute '__getitem__'
```
You'll notice that the `Association` is `None` here.

I looked further and found that this relates to instances in a Stopped state.

I'd love to dig further and submit a PR on this but am working from a very slow machine this week and it's frustrating as all hell, but figured it'd be useful to put here.

**Comment by l01cd3v** [comment]
Should be fixed

**Comment by d-j-c** [comment]
LGTM

**Comment by chilithomas** [comment]
**Reproduced the error:**
```
Traceback (most recent call last):
  File "./Scout2Listall.py", line 8, in <module>
    sys.exit(main())
  File "/Users/john_white/Scout2/AWSScout2/__listall__.py", line 110, in main
    (lines, template) = format_listall_output(args.format_file[0], None, args.format, rule)
TypeError: 'NoneType' object has no attribute '__getitem__'
```
**Fixed it by removing the [0] from format_file**
_vi  __listall__.py_

```
# Prepare the output format
110         (lines, template) = format_listall_output(args.format_file, None, args.format, rule)
```

**Comment by j4v** [comment]
@chilithomas could you please provide more details on the command you were running as well as --debug output? I'm not sure your issue is related to the above.

**Comment by j4v** [comment]
Closed dur to lack of update.
