### ISSUE TITLE
Failed to process rule defined in s3-bucket-world-acl.json?

### ISSUE THREAD

**Issue by grettir** [nccgroup/Scout2#195]
Scout2 is failing when checking s3 bucket ACLs in *one* of my AWS accounts. Oddly enough, it runs flawlessly in all of my other AWS accounts.

Here's the section of the log where the problems arise:

```
Processing CloudTrail config...
Analyzing VPC Network ACLs...
Matching VPC network ACLs and subnets...
None
Path: ['regions', u'us-east-1', 'vpcs', u'EC2-Classic', 'instances']
Key = instances
Value = i-xxxxxxxx
Path = []
Matching EC2 instances and IAM roles...
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'grantees']
Object: None
Entry target path: [u'id']

Failed to process rule defined in s3-bucket-world-acl.json
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'grantees']
Object: None
Entry target path: [u'id']

Failed to process rule defined in s3-bucket-world-acl.json
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'grantees']
Object: None
Entry target path: [u'id']

Failed to process rule defined in s3-bucket-world-acl.json
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'grantees']
Object: None
Entry target path: [u'id']

Failed to process rule defined in s3-bucket-world-acl.json
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'grantees']
Object: None
Entry target path: [u'id']

Failed to process rule defined in s3-bucket-world-acl.json
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'grantees']
Object: None
Entry target path: [u'id']

Failed to process rule defined in s3-bucket-world-acl.json
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'grantees']
Object: None
Entry target path: [u'id']

Failed to process rule defined in s3-bucket-world-acl.json
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'grantees']
Object: None
Entry target path: [u'id']

Failed to process rule defined in s3-bucket-world-acl.json
Traceback (most recent call last):
  File "./Scout2.py", line 8, in <module>
    sys.exit(main())
  File "/Users/xxxxxxx/Code/Scout2/AWSScout2/__main__.py", line 106, in main
    postprocessing(aws_config, report.current_time, finding_rules)
  File "/Users/xxxxxxx/Code/Scout2/AWSScout2/rules/postprocessing.py", line 20, in postprocessing
    update_last_run(aws_config, current_time, ruleset)
  File "/Users/xxxxxxx/Code/Scout2/AWSScout2/rules/postprocessing.py", line 41, in update_last_run
    if last_run['summary'][service]['max_level'] != 'danger' and len(aws_config['services'][service]['findings'][finding]['items']) > 0:
KeyError: 'items'
```

Running with `--debug` doesn't provide any additional (useful) information.

The problem only started in the past week or so, but I've tried rolling back the last few commits and that doesn't resolve the issue, so I'm not sure that a code change is to blame. On the other had, I can't think of any AWS account changes that would have caused the problem either.

Has anyone else seen this?

**Comment by danny13-33** [comment]
I've got the same thing but fails to process the rule defined in ec2-instance-with-open-nacls.json.  The problem just started for me too.

**Comment by mark-ignacio** [comment]
I think I fixed this in the PR linked above. @grettir and @danny13-33, do you mind testing this for me?
