### ISSUE TITLE
Running against GovCloud and it tries to use us-east-1 for S3

### ISSUE THREAD

**Issue by pittjl** [nccgroup/Scout2#210]
Scout2 3.1.0
cmd line: Scout2  --region us-gov-west-1

Fetching S3 config...
             buckets
'us-east-1''us-east-1'

                 0/2

verbose:

Fetching S3 config...
             buckets
Traceback (most recent call last):
  File "/Users/pittjl/envs/aws/lib/python2.7/site-packages/AWSScout2/configs/base.py", line 163, in __fetch_target
    method(target, params)
  File "/Users/pittjl/envs/aws/lib/python2.7/site-packages/AWSScout2/services/s3.py", line 41, in parse_buckets
    api_client = params['api_clients']['us-east-1']
KeyError: 'us-east-1'
Traceback (most recent call last):
  File "/Users/pittjl/envs/aws/lib/python2.7/site-packages/AWSScout2/configs/base.py", line 163, in __fetch_target
    method(target, params)
  File "/Users/pittjl/envs/aws/lib/python2.7/site-packages/AWSScout2/services/s3.py", line 41, in parse_buckets
    api_client = params['api_clients']['us-east-1']
KeyError: 'us-east-1'

If I change line 41 in s3.py to read us-gov-west-1, all is well.

**Comment by l01cd3v** [comment]
Thanks, I’ll try to get a fix for this.

**Comment by l01cd3v** [comment]
This should have been fixed -- Could you please confirm ? (no new version published yet, so you'll need to run it from a repo clone)

**Comment by pittjl** [comment]
Looks good, thanks!
