### ISSUE TITLE
Failure on run with suggested "read-only" IAM role

### ISSUE THREAD

**Issue by roens** [nccgroup/Scout2#243]
I've just tried running `Scout2` for the firs time. I created a new IAM API key for it, with a role attached as described [here](https://github.com/nccgroup/AWS-recipes/blob/112acd4b00d8e20592ed2629b2f7a3c1c67766c5/IAM-Policies/Scout2-Default.json). The steps I followed then:

1. `git clone https://github.com/nccgroup/Scout2`
2. `cd Scout2`
3. `sudo -H pip install -r requirements.txt`
4. `sudo python setup.py install`
5. `Scout2 --profile Scout2-Auditor`

It then produced the following output (private info redacted):
```
Fetching IAM config...
              groups           policies              roles              users  credential_report    password_policy
                 5/5              44/44              52/52              15/15                1/1                1/1
Fetching Route53Domains config...
             domains
                 1/1
Fetching SES config...
             regions         identities
                 3/3                1/1
Fetching RDS config...
             regions   parameter_groups          instances          snapshots    security_groups      subnet_groups
               15/15                3/3                3/3              82/82              15/15                2/2
Fetching CloudTrail config...
             regions             trails
               13/15              24/26An error occurred (AccessDeniedException) when calling the GetEventSelectors operation: User: arn:aws:iam::000000000000:user/Scout2-Auditor is not authorized to perform: cloudtrail:GetEventSelectors on resource: arn:aws:cloudtrail:us-west-2:000000000000:trail/Rackspace
               14/15              26/28An error occurred (AccessDeniedException) when calling the GetEventSelectors operation: User: arn:aws:iam::000000000000:user/Scout2-Auditor is not authorized to perform: cloudtrail:GetEventSelectors on resource: arn:aws:cloudtrail:us-east-1:000000000000:trail/CloudTrail
               15/15              28/30
Fetching ELB config...
             regions               elbs
               12/15                1/7An error occurred (AccessDenied) when calling the DescribeLoadBalancerPolicies operation: User: arn:aws:iam::000000000000:user/Scout2-Auditor is not authorized to perform: elasticloadbalancing:DescribeLoadBalancerPolicies
An error occurred (AccessDenied) when calling the DescribeLoadBalancerPolicies operation: User: arn:aws:iam::000000000000:user/Scout2-Auditor is not authorized to perform: elasticloadbalancing:DescribeLoadBalancerPolicies
               15/15                5/7
Fetching EFS config...
             regions       file_systems
                 6/6                0/0
Fetching ELBV2 config...
             regions                lbs       ssl_policies
                6/15                0/0                5/5An error occurred (AccessDenied) when calling the DescribeListeners operation: User: arn:aws:iam::000000000000:user/Scout2-Auditor is not authorized to perform: elasticloadbalancing:DescribeListeners
An error occurred (AccessDenied) when calling the DescribeListeners operation: User: arn:aws:iam::000000000000:user/Scout2-Auditor is not authorized to perform: elasticloadbalancing:DescribeListeners
An error occurred (AccessDenied) when calling the DescribeListeners operation: User: arn:aws:iam::000000000000:user/Scout2-Auditor is not authorized to perform: elasticloadbalancing:DescribeListeners
An error occurred (AccessDenied) when calling the DescribeListeners operation: User: arn:aws:iam::000000000000:user/Scout2-Auditor is not authorized to perform: elasticloadbalancing:DescribeListeners
An error occurred (AccessDenied) when calling the DescribeListeners operation: User: arn:aws:iam::000000000000:user/Scout2-Auditor is not authorized to perform: elasticloadbalancing:DescribeListeners
An error occurred (AccessDenied) when calling the DescribeListeners operation: User: arn:aws:iam::000000000000:user/Scout2-Auditor is not authorized to perform: elasticloadbalancing:DescribeListeners
               15/15                0/6                5/5
Fetching CloudWatch config...
             regions             alarms
               15/15            149/149
Fetching Lambda config...
             regions          functions
               15/15              10/10
Fetching RedShift config...
             regions   parameter_groups           clusters    security_groups
               15/15                0/0                0/0                0/0
Fetching S3 config...
             buckets
               31/31
Fetching CloudFormation config...
             regions             stacks
               15/15              93/93
Fetching SQS config...
             regions             queues
               15/15                5/5
Fetching EC2 config...
             regions          instances          snapshots network_interfaces            volumes    security_groups
               15/15              40/40            673/673              75/75              46/46              78/78
Fetching VPC config...
             regions            subnets       route_tables       vpn_gateways               vpcs  customer_gateways       network_acls    vpn_connections          flow_logs peering_connections
                0/15                2/2                0/0                0/0                0/0                0/0                             0/15                1/2                0/0                0/0                0/0                0/0                             0/15                3/5                0/0                0/0                0/0                0/0                             0/15                4/5                0/0                0/0                0/0                0/0                             0/15                5/5                0/0                0/0                0/0                0/0                             0/15                6/8                0/0                0/0                0/0                0/0                             0/15                7/8                0/0                0/0                0/0                0/0                             0/15                8/8                0/0                0/0                0/0                0/0                             0/15                8/8                1/1                0/0                0/0                0/0                             0/15                8/8                2/2                0/0                0/0                0/0                             0/15                8/8                3/3                0/0                0/0                0/0                             0/15                8/8                3/3                0/0                1/1                0/0                             0/15               9/10                3/3                0/0                1/1                0/0                             0/15              10/10                3/3                0/0                1/1                0/0                             0/15              11/12                3/3                0/0                1/1                0/0                             0/15              12/12                3/3                0/0                1/1                0/0                             0/15              13/15                3/3                0/0                1/1                0/0                             0/15              14/15                3/3                0/0                1/1                0/0                             0/15              15/15                3/3                0/0                1/1                0/0                             0/15              16/18                3/3                0/0                1/1                0/0                             0/15              17/18                3/3                0/0                1/1                0/0                             0/15              18/18                3/3                0/0                1/1                0/0                             0/15              19/21                3/3                0/0                1/1                0/0                             0/15              20/21                3/3                0/0                1/1                0/0                             0/15              21/21                3/3                0/0                1/1                0/0                             0/15              23/24                3/3                0/0                1/1                0/0                             0/15              22/24                3/3                0/0                1/1                0/0                             0/15              24/24                3/3                0/0                1/1                0/0                             0/15              24/24                3/3                0/0                2/2                0/0                             0/15              25/27                3/3                0/0                2/2                0/0                             0/15              26/27                3/3                0/0                2/2                0/0                             0/15              27/27                3/3                0/0                2/2                0/0                             0/15              27/27                4/4                0/0                2/2                0/0                             0/15              27/27                4/4                0/0                3/3                0/0                             0/15              27/27                5/5                0/0                3/3                0/0                             0/15              27/27                6/6                0/0                3/3                0/0                             0/15              27/27                7/7                0/0                3/3                0/0                             0/15              27/27                8/8                0/0                3/3                0/0                             0/15              27/27                9/9                0/0                3/3                0/0                             0/15              27/27                9/9                0/0                3/3                0/0                             0/15              27/27              10/10                0/0                3/3                0/0                             0/15              27/27              10/10                0/0                3/3                0/0                             0/15              27/27              10/10                0/0                4/4                0/0                             0/15              27/27              10/10                0/0                5/5                0/0                             0/15              27/27              10/10                0/0                5/5                0/0                             0/15              27/27              10/10                0/0                6/6                0/0                             0/15              27/27              10/10                0/0                7/7                0/0                             1/15              27/27              10/10                0/0                8/8                0/0                             1/15              27/27              10/10                0/0                8/9                0/0                             1/15              27/27              10/10                0/0               9/10                0/0                             1/15              27/27              10/10                0/0               9/10                0/0                             1/15              27/27              10/10                0/0              10/10                0/0                             1/15              27/27              10/10                0/0              10/10                0/0                             1/15              27/27              10/10                0/0              10/10                0/0                             3/15              27/27              10/10                0/0              10/10                0/0                             3/15              27/27              10/10                0/0              10/10                0/0                             3/15              27/27              10/10                0/0              10/10                0/0                             7/15              28/29              10/10                0/0              10/10                0/0                             7/15              29/29              10/10                0/0              10/10                0/0                             7/15              30/31              10/10                0/0              10/10                0/0                             7/15              31/31              10/10                0/0              10/10                0/0                             7/15              32/34              10/10                0/0              10/10                0/0                             7/15              33/34              10/10                0/0              10/10                0/0                             7/15              34/34              10/10                0/0              10/10                0/0                             7/15              34/34              11/11                0/0              10/10                0/0                             8/15              34/34              12/12                0/0              10/10                0/0                             8/15              35/52              12/12                0/0              10/10                0/0                             8/15              36/52              12/12                0/0              10/10                0/0                             8/15              37/52              12/12                0/0              10/10                0/0                             8/15              38/52              12/12                0/0              10/10                0/0                             8/15              39/52              12/12                0/0              10/10                0/0                             8/15              40/52              12/12                0/0              10/10                0/0                             8/15              41/52              12/12                0/0              10/10                0/0                             8/15              42/52              12/12                0/0              10/10                0/0                             8/15              43/52              12/12                0/0              10/10                0/0                             8/15              44/52              12/12                0/0              10/10                0/0                             8/15              45/52              12/12                0/0              10/10                0/0                             8/15              46/52              12/12                0/0              10/10                0/0                             8/15              47/52              12/12                0/0              10/10                0/0                             8/15              48/52              12/12                0/0              10/10                0/0                             8/15              49/52              12/12                0/0              10/10                0/0                             8/15              50/52              12/12                0/0              10/10                0/0                             8/15              51/52              12/12                0/0              10/10                0/0                             8/15              52/52              12/12                0/0              10/10                0/0                             8/15              52/52              12/12                0/0              11/11                0/0                             8/15              53/55              12/12                0/0              11/11                0/0                             8/15              54/55              12/12                0/0              11/11                0/0                             8/15              55/55              12/12                0/0              11/11                0/0                             8/15              55/55              13/13                0/0              11/11                0/0                            10/15              55/55              14/14                0/0              11/11                0/0                            10/15              55/55              14/14                0/0              11/11                0/0                            10/15              55/55              15/27                0/0              11/11                0/0                            10/15              55/55              16/27                0/0              11/11                0/0                            10/15              55/55              17/27                0/0              11/11                0/0                            10/15              55/55              18/27                0/0              11/11                0/0                            10/15              55/55              19/27                0/0              11/11                0/0                            10/15              55/55              20/27                0/0              11/11                0/0                            10/15              55/55              21/27                0/0              11/11                0/0                            10/15              55/55              22/27                0/0              11/11                0/0                            10/15              55/55              23/27                0/0              11/11                0/0                            10/15              55/55              24/27                0/0              11/11                0/0                            10/15              55/55              25/27                0/0              11/11                0/0                            10/15              55/55              26/27                0/0              11/11                0/0                            10/15              55/55              27/27                0/0              11/11                0/0                            10/15              55/55              27/27                0/0              12/12                0/0                            10/15              55/55              27/27                0/0              13/13                0/0                            11/15              55/55              27/27                1/3              13/13                0/0                            11/15              55/55              27/27                2/3              13/13                0/0                            11/15              55/55              27/27                3/3              13/13                0/0                            11/15              55/55              27/27                3/3              13/13                0/0                            11/15              55/55              27/27                3/3              13/13                0/0                            11/15              55/55              27/27                3/3              14/17                0/0                            11/15              55/55              27/27                3/3              15/17                0/0                            11/15              55/55              27/27                3/3              16/17                0/0                            11/15              55/55              27/27                3/3              17/17                0/0                            11/15              55/55              27/27                3/3              18/18                0/0                            12/15              55/55              27/27                3/3              18/18                1/1                            12/15              55/55              27/27                3/3              18/18                1/1                            12/15              55/55              27/27                3/3              18/18                1/1                            12/15              55/55              27/27                3/3              18/18                1/1                            12/15              55/55              27/27                3/3              18/18                1/1                            13/15              55/55              27/27                3/3              18/18                1/1                            13/15              55/55              27/27                3/3              18/18                1/1                            13/15              55/55              27/27                3/3              18/18                1/1                            13/15              55/55              27/27                3/3              18/18                1/1                            13/15              55/55              27/27                3/3              18/18                1/1                            13/15              55/55              27/27                3/3              18/18                1/1                            14/15              55/55              27/27                3/3              18/18                1/1                            14/15              55/55              27/27                3/3              18/18                1/1                            15/15              55/55              27/27                3/3              18/18                1/1              18/18                3/3                2/2                2/2
Fetching EMR config...
             regions           clusters
               15/15                0/0
Fetching Direct Connect config...
             regions        connections
               15/15                0/0
Fetching ElastiCache config...
             regions           clusters    security_groups
               15/15                0/0                0/0
Fetching Route53 config...
        hosted_zones
                 5/5
Fetching SNS config...
             regions             topics      subscriptions
               15/15              98/98              16/16
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/Scout2", line 11, in <module>
    load_entry_point('AWSScout2==3.2.0', 'console_scripts', 'Scout2')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/AWSScout2-3.2.0-py2.7.egg/AWSScout2/__main__.py", line 74, in main
    aws_config['aws_account_id'] = get_aws_account_id(credentials)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/opinel/utils/aws.py", line 99, in get_aws_account_id
    caller_identity = get_caller_identity(credentials)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/opinel/utils/aws.py", line 90, in get_caller_identity
    return api_client.get_caller_identity()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 602, in _make_api_call
    operation_model, request_dict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://sts.amazonaws.com/"
```

My first guess is: does everyone just run `Scout2` with their default `FullAccess` credentials? :-D

**Comment by l01cd3v** [comment]
I am not good at updating the default policy as I add features to the tool - I'll fix it.

**Comment by parthmishra** [comment]
@l01cd3v is this an issue with the default policy? What needs to be added in order to fix it?

**Comment by j4v** [comment]
The documentation has been updated to recommend using Managed Policies.
