### ISSUE TITLE
S3 rules break on buckets with no ACLs - Error: unhandled case, typeof(current_info) = <type 'NoneType'>

### ISSUE THREAD

**Issue by hb3b** [nccgroup/Scout2#252]
We have a number of buckets that have been wiped of their ACLs such that only the root account can access them. When Scout2 comes across these buckets, the s3-bucket-world-acl.json rule fails and doesn't flag any buckets in the report.

<img width="1325" alt="screen shot 2018-03-20 at 4 09 41 pm" src="https://user-images.githubusercontent.com/6397627/37680046-23146184-2c59-11e8-9335-567a3afbd6ee.png">

<img width="790" alt="screen shot 2018-03-20 at 3 42 52 pm" src="https://user-images.githubusercontent.com/6397627/37680171-7854d890-2c59-11e8-92cf-c998f3fa9d2c.png">

```
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket world-listable (anonymous)"
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'---BUCKET-GUID---', u'grantees']
Object: None
Entry target path: [u'id']
Traceback (most recent call last):
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/processingengine.py", line 50, in run
    aws_config['services'][service][self.ruleset.rule_type][rule.key]['items'] = recurse(aws_config['services'], aws_config['services'], path, [], rule, True)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 78, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 90, in recurse
    raise Exception
Exception

Failed to process rule defined in s3-bucket-world-acl.json
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket's permissions world-readable (anonymous)"
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'---BUCKET-GUID---', u'grantees']
Object: None
Entry target path: [u'id']
Traceback (most recent call last):
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/processingengine.py", line 50, in run
    aws_config['services'][service][self.ruleset.rule_type][rule.key]['items'] = recurse(aws_config['services'], aws_config['services'], path, [], rule, True)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 78, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 90, in recurse
    raise Exception
Exception

Failed to process rule defined in s3-bucket-world-acl.json
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket world-writable (anonymous)"
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'---BUCKET-GUID---', u'grantees']
Object: None
Entry target path: [u'id']
Traceback (most recent call last):
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/processingengine.py", line 50, in run
    aws_config['services'][service][self.ruleset.rule_type][rule.key]['items'] = recurse(aws_config['services'], aws_config['services'], path, [], rule, True)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 78, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 90, in recurse
    raise Exception
Exception

Failed to process rule defined in s3-bucket-world-acl.json
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket's permissions world-writable (anonymous)"
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'---BUCKET-GUID---', u'grantees']
Object: None
Entry target path: [u'id']
Traceback (most recent call last):
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/processingengine.py", line 50, in run
    aws_config['services'][service][self.ruleset.rule_type][rule.key]['items'] = recurse(aws_config['services'], aws_config['services'], path, [], rule, True)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 78, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 90, in recurse
    raise Exception
Exception

Failed to process rule defined in s3-bucket-world-acl.json
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket world-listable"
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'---BUCKET-GUID---', u'grantees']
Object: None
Entry target path: [u'id']
Traceback (most recent call last):
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/processingengine.py", line 50, in run
    aws_config['services'][service][self.ruleset.rule_type][rule.key]['items'] = recurse(aws_config['services'], aws_config['services'], path, [], rule, True)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 78, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 90, in recurse
    raise Exception
Exception

Failed to process rule defined in s3-bucket-world-acl.json
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket's permissions world-readable"
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'---BUCKET-GUID---', u'grantees']
Object: None
Entry target path: [u'id']
Traceback (most recent call last):
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/processingengine.py", line 50, in run
    aws_config['services'][service][self.ruleset.rule_type][rule.key]['items'] = recurse(aws_config['services'], aws_config['services'], path, [], rule, True)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 78, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 90, in recurse
    raise Exception
Exception

Failed to process rule defined in s3-bucket-world-acl.json
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket world-writable"
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'---BUCKET-GUID---', u'grantees']
Object: None
Entry target path: [u'id']
Traceback (most recent call last):
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/processingengine.py", line 50, in run
    aws_config['services'][service][self.ruleset.rule_type][rule.key]['items'] = recurse(aws_config['services'], aws_config['services'], path, [], rule, True)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 78, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 90, in recurse
    raise Exception
Exception

Failed to process rule defined in s3-bucket-world-acl.json
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket's permissions world-writable"
Error: unhandled case, typeof(current_info) = <type 'NoneType'>
Path: [u's3', u'buckets', u'---BUCKET-GUID---', u'grantees']
Object: None
Entry target path: [u'id']
Traceback (most recent call last):
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/processingengine.py", line 50, in run
    aws_config['services'][service][self.ruleset.rule_type][rule.key]['items'] = recurse(aws_config['services'], aws_config['services'], path, [], rule, True)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 78, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 71, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/hb3b/person/Scout2/AWSScout2/rules/utils.py", line 90, in recurse
    raise Exception
Exception

Failed to process rule defined in s3-bucket-world-acl.json
```

**Comment by hb3b** [comment]
Here is a workaround that we'll use in the mean time.

https://github.com/hb3b/Scout2/commit/34c072270366ec3bde34c8aa1c0ee7a266f8e59b

Since I'm not familiar with the codebase, I'd appreciate further direction.
