### ISSUE TITLE
KeyError: 'Name' in EFS service

### ISSUE THREAD

**Issue by andresriancho** [nccgroup/Scout2#293]
```
Traceback (most recent call last):
  File "/home/andres/tools/virtualenvs/scout2/local/lib/python2.7/site-packages/AWSScout2-3.2.1-py2.7.egg/AWSScout2/configs/regions.py", line 186, in _fetch_target
    method(params, region, target)
  File "/home/andres/tools/virtualenvs/scout2/local/lib/python2.7/site-packages/AWSScout2-3.2.1-py2.7.egg/AWSScout2/services/efs.py", line 29, in parse_file_system
    file_system['name'] = file_system.pop('Name')
KeyError: 'Name'
```

**Comment by j4v** [comment]
Could you please provide more details about the issue (full output with `--debug` flag) please.
