### ISSUE TITLE
KeyError: None in rules/preprocessing.py

### ISSUE THREAD

**Issue by andresriancho** [nccgroup/Scout2#294]
```
Traceback (most recent call last):
  File "/home/andres/tools/virtualenvs/scout2/local/lib/python2.7/site-packages/AWSScout2-3.2.1-py2.7.egg/AWSScout2/rules/preprocessing.py", line 632, in new_go_to_and_do
    callback(aws_config, current_config[key][value], path, current_path, value, callback_args)
  File "/home/andres/tools/virtualenvs/scout2/local/lib/python2.7/site-packages/AWSScout2-3.2.1-py2.7.egg/AWSScout2/rules/preprocessing.py", line 284, in match_instances_and_subnets_callback
    vpc = subnet_map[subnet_id]
KeyError: None
```

**Comment by j4v** [comment]
Could you please provide more details about the issue (full output with `--debug` flag) please.

**Comment by j4v** [comment]
Merged into https://github.com/nccgroup/Scout2/issues/296.
