### ISSUE TITLE
Fails When Analyzing VPCs

### ISSUE THREAD

**Issue by vitalisec** [nccgroup/Scout2#91]
git pull is up-to-date.

```
Analyzing VPC config...
Traceback (most recent call last):
  File "./Scout2.py", line 237, in <module>
    sys.exit(main(args))
  File "./Scout2.py", line 125, in main
    analyze_vpc_config(aws_config, args.ip_ranges, args.ip_ranges_key_name)
  File "/Users/travis.schack/Documents/Code/Python/Scout2/AWSScout2/utils_vpc.py", line 20, in analyze_vpc_config
    go_to_and_do(aws_config, aws_config['services']['ec2'], ['regions', 'vpcs', 'elbs'], ['services', 'ec2'], list_resources_in_security_group, callback_args)
  File "/Users/travis.schack/Documents/Code/Python/Scout2/AWSScout2/utils.py", line 155, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/Users/travis.schack/Documents/Code/Python/Scout2/AWSScout2/utils.py", line 155, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/Users/travis.schack/Documents/Code/Python/Scout2/AWSScout2/utils.py", line 147, in go_to_and_do
    callback(aws_config, current_config[key][value], path, current_path, value, callback_args)
  File "/Users/travis.schack/Documents/Code/Python/Scout2/AWSScout2/utils_vpc.py", line 62, in list_resources_in_security_group
    sg = get_object_at(aws_config, sg_path)
  File "/Users/travis.schack/Documents/Code/Python/Scout2/AWSScout2/utils.py", line 127, in get_object_at
    o = o[p]
KeyError: 'security_groups'

```

**Comment by fbardella-zd** [comment]
same here... 

Analyzing VPC config...
Traceback (most recent call last):
  File "./Scout2.py", line 237, in <module>
    sys.exit(main(args))
  File "./Scout2.py", line 125, in main
    analyze_vpc_config(aws_config, args.ip_ranges, args.ip_ranges_key_name)
  File "/Users/fbardella/SEC/aws/Scout2/AWSScout2/utils_vpc.py", line 20, in analyze_vpc_config
    go_to_and_do(aws_config, aws_config['services']['ec2'], ['regions', 'vpcs', 'elbs'], ['services', 'ec2'], list_resources_in_security_group, callback_args)
  File "/Users/fbardella/SEC/aws/Scout2/AWSScout2/utils.py", line 155, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/Users/fbardella/SEC/aws/Scout2/AWSScout2/utils.py", line 155, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/Users/fbardella/SEC/aws/Scout2/AWSScout2/utils.py", line 147, in go_to_and_do
    callback(aws_config, current_config[key][value], path, current_path, value, callback_args)
  File "/Users/fbardella/SEC/aws/Scout2/AWSScout2/utils_vpc.py", line 62, in list_resources_in_security_group
    sg = get_object_at(aws_config, sg_path)
  File "/Users/fbardella/SEC/aws/Scout2/AWSScout2/utils.py", line 127, in get_object_at
    o = o[p]
KeyError: 'security_groups'

**Comment by fbardella-zd** [comment]
@l01cd3v do you need more data to fix this issue ?

**Comment by l01cd3v** [comment]
Yes, could you do the following:

- Confirm the command used to run the tool
- use --debug to get a more verbose data
- Let me know what permissions the user running the tool has

Thanks

**Comment by l01cd3v** [comment]
This should be fixed in master now
